import { Bar } from './components/bar/Bar';
import { Navbar } from './components/navbar/Navbar';
import './globals.css';

import localFont from 'next/font/local';
const myFont = localFont({
	src: './TheWyomingFont.ttf',
});
export const metadata = {
	title: 'Instagram.exe',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={myFont.className}>
				<div className="WindowsContainer">
					<div className="Container">
						<Navbar />
						<Bar />
					</div>
				</div>
				{children}
			</body>
		</html>
	);
}
