import { Inter } from 'next/font/google';
import './globals.css';
import { Navbar } from './components/navbar/Navbar';

const inter = Inter({ subsets: ['latin'] });
import localFont from 'next/font/local';
// const myFont = localFont({
// 	src: './SSERIFE.FON',
// 	display: 'swap',
// 	type: 'fon',
// });
export const metadata = {
	title: 'Instagram.exe',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
